### ISSUE TITLE
Make cannot find Lua

### ISSUE THREAD

**Issue by Pythone** [LibreSprite/Dotto#12]
The package I installed for Lua was Lua5.3, make cannot find the package for Lua because I could not use the default package name.

Package lua was not found in the pkg-config search path.
Perhaps you should add the directory containing `lua.pc'
to the PKG_CONFIG_PATH environment variable
No package 'lua' found
g++ -Og -g -D_DEBUG  -Ilibs -Ilibs/tinyxml2 -Ilibs/duktape -Ilibs/tinyfiledialogs -Isrc -MMD -MP -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/freetype2 -I/usr/include/libpng16 -DSCRIPT_ENGINE_LUA  --std=c++17 -c src/cmd/Paint.cpp -o build/src/cmd/Paint.cpp.o
Package lua was not found in the pkg-config search path.
Perhaps you should add the directory containing `lua.pc'
to the PKG_CONFIG_PATH environment variable
No package 'lua' found
g++ -Og -g -D_DEBUG  -Ilibs -Ilibs/tinyxml2 -Ilibs/duktape -Ilibs/tinyfiledialogs -Isrc -MMD -MP -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/freetype2 -I/usr/include/libpng16 -DSCRIPT_ENGINE_LUA  --std=c++17 -c src/cmd/ActivateTool.cpp -o build/src/cmd/ActivateTool.cpp.o
^Cmake: *** [Makefile:101: build/src/cmd/ActivateTool.cpp.o] Interrupt

I am using Pop!_OS 20.04. Where do you think the path would be?

**Comment by orbitalmartian8** [comment]
It should work. I’ve just looked at the files that I think could affect this and they seem to be in order. Maybe try rebooting your system to complete the install of Lua (ik that some things need a system reboot to finish installing)

**Comment by felipemanga** [comment]
Can you check again? This should be fixed now.
