### ISSUE TITLE
UI looking comically small on my monitor

### ISSUE THREAD

**Issue by velllu** [LibreSprite/Dotto#14]
![2022-02-06_19-00](https://user-images.githubusercontent.com/91963404/152694626-9d5ad6aa-e0cc-4c0a-beff-2fb38daa0ec8.png)

Steps to reproduce:
1. Come to my house
2. Open the program
3. Observe

**Comment by RomanSedykh** [comment]
settings.ini. increase this number to your taste.
![image](https://user-images.githubusercontent.com/59629258/152695248-0d3f9d26-ecab-4a4e-89ad-45cd525696df.png)

**Comment by jjhaggar** [comment]
I love the "steps to reproduce" XD

**Comment by orbitalmartian8** [comment]
The absolute best and also tbh the proper answer ngl.
