### ISSUE TITLE
Windows lib failure

### ISSUE THREAD

**Issue by nullified33** [LibreSprite/Dotto#15]
![image](https://user-images.githubusercontent.com/70713233/155650930-6446f686-c2c4-4ed4-8f2d-ea5ddb9df3b1.png)
![image](https://user-images.githubusercontent.com/70713233/155651041-d760b408-a492-4a9b-97d8-a007bcee347f.png)
![image](https://user-images.githubusercontent.com/70713233/155651055-043e56f9-27d9-4b12-a67a-3ee5af085edf.png)
![image](https://user-images.githubusercontent.com/70713233/155651088-96f51f94-d5db-412a-803f-a00fc8493a9c.png)

**Comment by nullified33** [comment]
![image](https://user-images.githubusercontent.com/70713233/155652110-7d50ca62-48be-4405-b710-f72cfde7b7e7.png)
![image](https://user-images.githubusercontent.com/70713233/155652143-810ebf1b-a341-4167-975f-287b952fdf7b.png)
also

**Comment by orbitalmartian8** [comment]
Is this from the newest commits?

**Comment by felipemanga** [comment]
This is expected, I'm still setting up Windows builds and the windows-specific parts of the code aren't in this repo yet.

**Comment by felipemanga** [comment]
Fixed.

**Comment by 3prm3** [comment]
> Is this from the newest commits?

yes

**Comment by nullified33** [comment]
works on latest version
