### ISSUE TITLE
Could not load language [en_US]

### ISSUE THREAD

**Issue by z3roco01** [LibreSprite/Dotto#17]
Im on gentoo trying to run dotto and it give me the error `Could not load language [en_US]` and doesn't run

**Comment by felipemanga** [comment]
This isn't an error, it should run normally even though it didn't find en_US. 
Is there any other message? Are you running the CI build or did you make your own?
A debug build has more verbose logs, can you try that instead of a release build? 

```sh
make clean
make DEBUG=true
./dotto
```

**Comment by z3roco01** [comment]
I am building it on my own.
[Output](https://github.com/LibreSprite/Dotto/files/8227735/output.txt) from dotto build with debug on

**Comment by felipemanga** [comment]
Can you try [this](https://github.com/LibreSprite/Dotto/releases/tag/v0.1) build and tell me if it behaves the same?

**Comment by z3roco01** [comment]
It gives a seg fault

**Comment by felipemanga** [comment]
Can you pull and recompile? It should be fixed now.

**Comment by z3roco01** [comment]
It says `Running Dotto!` but nothing else happens, theres no gui or anything

**Comment by orbitalmartian8** [comment]
> It says `Running Dotto!` but nothing else happens, theres no gui or anything

Have you tried recently? Is it still giving the same issue?

**Comment by z3roco01** [comment]
i'll try it when i get home

**Comment by maujin111** [comment]
Closing issue due to lack of update
