### ISSUE TITLE
Software Requirements for OSX Version Undocumented

### ISSUE THREAD

**Issue by pixlxip** [LibreSprite/Dotto#20]
The OSX version of v0.1 doesn't work with OSX 10.11.6 but there is nowhere that mentions the restrictions.
![Screen Shot 2022-03-17 at 6 12 04 PM](https://user-images.githubusercontent.com/99521063/158913725-686c3dc2-24db-414a-be73-e26418b11ec7.png)

**Comment by BIueish** [comment]
You could update to MacOS 12 or use Wine with the Windows version

**Comment by felipemanga** [comment]
It is undocumented because it isn't in stone yet.
Currently the CI builds require 12.1, but I suspect we can safely set it for 10.15. 
Supporting older MacOS's (10.9, maybe?) should be possible, but will require porting work.
