### ISSUE TITLE
Gui not loading correctly

### ISSUE THREAD

**Issue by Wolve-Chen** [LibreSprite/Dotto#25]
Compiled the git repository on Arch Linux,
while starting I get following error:

Could not create St10shared_ptrI11PropertySetE out of Dn

System:
Arch Linux "rolling" with Mate Desktop on a Dell E4310
gcc version 12.1.0
GNU make 4.3

Any clue how to fix this?

**Comment by felipemanga** [comment]
Yeah, this broke due to a refactor and is currently being worked on.

**Comment by felipemanga** [comment]
This should've been fixed some time ago. If any problems persist, feel free to open a new issue.
