### ISSUE TITLE
Confused on how to compile on Mac

### ISSUE THREAD

**Issue by jubiq** [LibreSprite/Dotto#26]
im a bit confused on what to do when compiling Dotto on Mac

**Comment by pegvin** [comment]
You'll Need To Have https://brew.sh installed, then you'll have to install some libraries needed by Dotto which can be done via this command:

```bash
brew install sdl2 sdl2_image lcms2 freetype v8 openssl pkg-config
```

after that first you'll need to clone the repository with all the submodules which can be done via this command:

```bash
git clone https://github.com/LibreSprite/Dotto --recursive
```

and go inside the cloned directory via cd command `cd Dotto/`
then just compile the program via make:

```bash
make DEBUG=true -j 4
```

replace the `4` in the above command with the number of cores you want/have.
