### ISSUE TITLE
Couldn't Launch on Windows Because Of Missing Library

### ISSUE THREAD

**Issue by pegvin** [LibreSprite/Dotto#27]
On Windows 10 I Cannot Launch The Latest GitHub Actions Build Because [libjxl](https://packages.msys2.org/package/mingw-w64-x86_64-libjxl) was not found, basically the libjxl.dll isn't included in the build.

**Comment by pegvin** [comment]
Screenshot

![Screenshot (45)](https://user-images.githubusercontent.com/75035219/190915566-7824901c-a805-41c0-9e88-19f9c25d8ff0.png)

**Comment by felipemanga** [comment]
This is a known issue. I think SDL2 got an update and this broke. 
I didn't want to have to go manually hunting for libs every time there was an update, but I still haven't found an alternative.

**Comment by pegvin** [comment]
ah fine, i'll make a PR for it.

edit: sorry i wasn't able to make a pr

**Comment by felipemanga** [comment]
This got fixed, at least until the next library update breaks something again.
