### ISSUE TITLE
Delete key on keyboard doesn't work when entering canvas size, and other keyboard shortcuts don't work

### ISSUE THREAD

**Issue by mak448a** [LibreSprite/Dotto#34]
**Describe the bug**
When entering the canvas size, pressing the delete key on the keyboard doesn't delete the number in front of the cursor.

**To Reproduce**
1. Go to File
2. Click on New
3. Click on Width box
4. Try putting the cursor one character back, then press the delete key on your keyboard

**Expected behavior**
The delete key should delete the character in front of the cursor.

 - OS: Fedora Linux 37
 - Browser: Firefox

**Comment by pixlxip** [comment]
Also, end and home don't work. Home should bring you to the start, and end should bring you to the end, but neither work.

**Comment by pegvin** [comment]
it's not really a bug, instead the case isn't handled, in the implementation, only <kbd>Arrow Left/Right</kbd> & <kbd>Backspace</kbd> are handled, so keys like <kbd>Delete</kbd>, <kbd>Home</kbd> & <kbd>End</kbd> are not handled.

**Comment by pegvin** [comment]
@mak448a PR #38 fixed this issue, please test it again and close the issue if resolved.

**Comment by felipemanga** [comment]
Fix confirmed, closing.

**Comment by mak448a** [comment]
Thank you! It works!
