### ISSUE TITLE
Is the compilation process supposed to take a few minutes?

### ISSUE THREAD

**Issue by mak448a** [LibreSprite/Dotto#49]
I haven't learned too much about C++ after the basics. So should compiling a project like this take a long time?

**Comment by pegvin** [comment]
not really, compiling a individual file is really fast on an average computer but when tons & tons of files are to be compiled it starts to take time.

unfortunately when compiling a project this large for the first time, yea things get really slow, but you can always use `-j<num-jobs>` with GNU Make or `--parallel <num-jobs>` in cmake to parallel-y compile multiple files which speeds up the process by alot!

now fortunately another way to speed up this process is not rebuilding anything which has not changed, most of programs like GNU Make & CMake basically compare the time when a particular file was changed and if it was built or not, if it was changed but wasn't built, it will be then re-built.

so for the first time it will take some time but then after when you re-compile only the things that have changed will be re-built.

**Comment by mak448a** [comment]
So basically, first compile times are huge, but later compiling is fast. Thanks!

**Comment by mak448a** [comment]
So basically, first compile times are huge, but later compiling is fast. Thanks!
