### ISSUE TITLE
Doesn't compile (qoi.h no such file or directory)

### ISSUE THREAD

**Issue by mak448a** [LibreSprite/Dotto#52]
**Describe the bug**
Doesn't compile

**To Reproduce**
Steps to reproduce the bug:
1. Environment: Fedora 38 KDE
2. Install dependencies in README.md
3. Run `make -j 8` in terminal
```shell
src/parsers/QoiParser.cpp:5:10: fatal error: qoi/qoi.h: No such file or directory
    5 | #include <qoi/qoi.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:175: build/src/parsers/QoiParser.cpp.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Expected behavior**
Should compile

**Comment by pegvin** [comment]
check if your Dotto's source directory has the following files:
- `dependencies/qoi/qoi.cpp`
- `dependencies/qoi/qoi.h`

if not, this means you didn't pull the submodules, basically Dotto has few third party libraries that are kept at [LibreSprite/DottoDependencies](https://github.com/LibreSprite/DottoDependencies/).

but there is a shortcut to this repository in the main dotto repository which is called a "submodule".

while cloning the repository you need to pass a flag `--recursive` which clones all the submodules too but you probably forgot that.

so if you don't want to re-clone everything you can run this command in your existing cloned repo:
```
git submodule update --init --recursive
```

**Comment by mak448a** [comment]
Oh ok  sorry I didn't follow the instructions properly
