### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by mak448a** [LibreSprite/Dotto#57]
It's a nice to have, but not necessary

**Comment by felipemanga** [comment]
No plans for working on anything Wayland specific any time soon. 
Supporting Windows, Mac, X11, Android, 3DS, and Emscripten is work enough.

**Comment by pegvin** [comment]
Dotto Uses SDL2 Under The Hood on Linux, So You Might Find This Useful - https://wiki.archlinux.org/title/wayland#SDL2
